name: 'Expand AWS IAM Wildcards'
description: 'Helps PR reviewers understand IAM wildcards by expanding them in inline comments, linking each matched action to AWS documentation.'
author: 'Kevin Behrens <kevin@thekbb.net>'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  file-patterns:
    description: 'Glob patterns for files to scan (comma-separated)'
    required: false
    default: '**/*.json,**/*.yaml,**/*.yml,**/*.tf,**/*.ts,**/*.js'
  collapse-threshold:
    description: 'Number of expanded actions before collapsing into details element'
    required: false
    default: '5'

runs:
  using: 'node20'
  main: 'dist/index.js'
